## Task #1

Решить систему уравнений методом Гаусса:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

In [6]:
import numpy as np

In [26]:
mx = np.array([
    [1.0, 1.0, -1.0, -2.0, 0.0], 
    [2.0, 1.0, -1.0, 1.0, -2.0], 
    [1.0, 1.0, -3.0, 1.0, 4.0]
])
mx

array([[ 1.,  1., -1., -2.,  0.],
       [ 2.,  1., -1.,  1., -2.],
       [ 1.,  1., -3.,  1.,  4.]])

In [27]:
mx[1] -= 2 * mx[0]
mx

array([[ 1.,  1., -1., -2.,  0.],
       [ 0., -1.,  1.,  5., -2.],
       [ 1.,  1., -3.,  1.,  4.]])

In [28]:
mx[2] -= mx[0]
mx

array([[ 1.,  1., -1., -2.,  0.],
       [ 0., -1.,  1.,  5., -2.],
       [ 0.,  0., -2.,  3.,  4.]])

In [29]:
mx[0] += mx[1]
mx

array([[ 1.,  0.,  0.,  3., -2.],
       [ 0., -1.,  1.,  5., -2.],
       [ 0.,  0., -2.,  3.,  4.]])

In [30]:
mx[1] += 0.5 * mx[2]
mx

array([[ 1. ,  0. ,  0. ,  3. , -2. ],
       [ 0. , -1. ,  0. ,  6.5,  0. ],
       [ 0. ,  0. , -2. ,  3. ,  4. ]])

In [33]:
x_4 = 12
x_1 = - 2 - 3 * x_4
x_2 = 6.5 * x_4
x_3 = 3/2 * x_4 - 2

In [34]:
x_1 + x_2 - x_3 - 2 * x_4

0.0

In [35]:
2 * x_1 + x_2 - x_3 + x_4

-2.0

In [36]:
x_1 + x_2 - 3 * x_3 + x_4

4.0

In [38]:
print(f'X = [{x_1}, {x_2}, {x_3}, {x_4}]')

X = [-38, 78.0, 16.0, 12]


## Task #2

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [41]:
arr = np.array([
    [3, -1, 1], 
    [2, -5, -3], 
    [1, 1, -1]
])
arr

array([[ 3, -1,  1],
       [ 2, -5, -3],
       [ 1,  1, -1]])

In [42]:
np.linalg.det(arr)

32.0

Определитель не равен нулю, кол-во переменных равно кол-ву уравнений, значит существует одно решение. Система совместна.

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [43]:
arr = np.array([
    [2, -4, 6], 
    [1, -2, 3], 
    [3, -6, 9]
])
arr

array([[ 2, -4,  6],
       [ 1, -2,  3],
       [ 3, -6,  9]])

In [44]:
np.linalg.det(arr)

0.0

Определитель равен нулю, значит СЛАУ не имеет решений. Система несовместна.

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Кол-во переменных больше кол-ва уравнений, значит существует бесконечное множество решений. Система совместна.

## Task #3

Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

$rank A=rank \tilde A$ - система совместна и имеет одно решение

In [48]:
x_4 = 1/2
x_3 = 4/3
x_2 = (2 - x_4)/5
x_1 = 3 - 3 * x_2 + 2 * x_3 - 4 * x_4

In [49]:
print(f'X = [{x_1}, {x_2}, {x_3}, {x_4}]')

X = [2.7666666666666666, 0.3, 1.3333333333333333, 0.5]


## Task #4

Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной

Вычтем из третьей строки две вторых

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
-1 & -2 & -3
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c-2b
\end{matrix}
\end{pmatrix}$

Прибавим к третьей строке первую

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c-2b+a
\end{matrix}
\end{pmatrix}$

Если $с \neq 2b - a$, то система будет несовместна. 