## Task #1

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [15]:
a = np.array([
    [1, 2, 0],
    [0, 0, 5],
    [3, -4, 2],
    [1, 6, 5],
    [0, 1, 0]
])


In [16]:
u, s, w = np.linalg.svd(a)
v = w.T

In [31]:
s

array([8.82, 6.14, 2.53])

In [19]:
d = np.zeros_like(a, dtype=float)
d[np.diag_indices(min(a.shape))] = s

In [26]:
u

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [27]:
d

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [28]:
v

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [30]:
np.dot(np.dot(u, d), v.T)

array([[ 1.,  2., -0.],
       [-0.,  0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [ 0.,  1.,  0.]])

### $\left \| A \right \|_{E}=\mu_{1}=8.82$

In [51]:
np.linalg.norm(a)

11.045361017187261

In [49]:
np.sqrt(sum(mu**2 for mu in s))

11.045361017187265

### $\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}} = 11.05$